### ISSUE TITLE
characters are displayed in reverse

### ISSUE THREAD

**Issue by ferengi82** [JennaSys/micropython-max7219#1]
hi,

im a absolute programming beginner, so i think i did something wrong.
maybe you can help me.

Im trying to display some numbers on an max7219 display. i wired all up to my esp32 and uploaded the code.
it is displaying the numbers, but in reverse:
display.number(3.14159)
=> 951413. on the display.

some advice would be nice

**Comment by JennaSys** [comment]
The fact you are actually getting the digits to show up, display the proper segments, and cascade properly, is a good sign.  It sounds like you might just need to reverse the order of how the digit lines (Dig0-Dig7) are connected to the displays.  Is this how they are hooked up:

> digit0 is the leftmost and digit7 is rightmost for each MAX7219 device. Cascaded devices add additional digits to the right.

**Comment by ferengi82** [comment]
i think i cant do that, its a module like this 
![image](https://user-images.githubusercontent.com/5311407/100268554-84b34980-2f55-11eb-8b22-d4542aa02f7b.png)
any way to change it in the code?
tried already to reverse the MAX7219_REG_DIGIT values, but it diddnt work

**Comment by ferengi82** [comment]
ok, i added this to the number function, maybe not the elegantest way, but i think its working

```
        s = strval
        strval = ""
        for i in s:
            strval = i + strval

        listval = list(strval)
        old_index = listval.index('.')
        strval = listval.pop(old_index)
        listval.insert(old_index+1, strval)
        strval = ''.join(listval)
        print(strval)
```

**Comment by JennaSys** [comment]
I see, so the module must be wired differently.  I suppose a flag could be added to reverse the string in cases like that.

You can reverse a string in Python with `strval[::-1]` or `"".join(reversed(strval))`

**Comment by ferengi82** [comment]
strval[::-1] was my first try, but i cant get it to work (micropython limitation?)
besides the reverse string you have to move the decimal point on to the right => code from above.

**Comment by doboyr** [comment]
Hi, Another beginner here that came across the exact same problem with a differently wired module and I found a slightly simpler solution by modifying 2 lines of the flush function definition.

on line 72 put 'reversed()' around 'range(self.scan_digits)' to write out to the digits in reverse order
`for pos in reversed(range(self.scan_digits)):`

and then changed line 73 so it doesn't read from the buffer backwards

`self._buffer[pos + (dev * self.scan_digits)]`
to
`self._buffer[(7 - pos) + (dev * self.scan_digits)]`

If I was more confident in my code I'd try implement the reverse iteration more elegantly and submit a pull request but hope this will save some others the stress I went through 🤯

**Comment by JennaSys** [comment]
That looks like an easy enough modification to include.  It's been a while since I was in this code, but I'll take a look at it and add an optional parameter to reverse it.

**Comment by JennaSys** [comment]
I ordered one of these modules for testing and will update the library soon.

**Comment by RSAlperen** [comment]
Hi;
I use 4 digits and modified to flush func;
```python
def flush(self):
        """For each digit, cascade out the contents of the buffer cells to the SPI device."""
        for dev in range(self.devices):
            for pos in reversed(range(self.scan_digits)):
                self._write([pos + MAX7219_REG_DIGIT0, self._buffer[((self.scan_digits - 1) - pos) + (dev * self.scan_digits)]] + ([MAX7219_REG_NOOP, 0] * dev))
```
and that work perfectly :)

**Comment by gerwinbrunner** [comment]
This is not yet merged, into master?

**Comment by JennaSys** [comment]
I needed to test it with the hardware but it fell off my radar tbh. I'll try and get to it this week.

**Comment by Andrew-Mullane** [comment]
@doboyr here on a different account, have just submitted a pull request with reverse flag added to the SevenSegment init that works great on my differently wired board.

**Comment by JennaSys** [comment]
Sorry this took so long, pulling all the hardware out that I needed to test it with led to my procrastination. The latest version has the ability to reverse the digits for displays that are wired R-to-L.
Thank you @Andrew-Mullane for the help.
